[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckTimeout = 100
healthcheckInterval = 30

[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."

[monitoring]
metrics = ["cpu", "memory", "disk", "network"]
alerts = [
    { metric = "cpu", threshold = 80, duration = "5m" },
    { metric = "memory", threshold = 85, duration = "5m" },
    { metric = "disk", threshold = 90, duration = "5m" }
]
logs = { retention = "7d", level = "info" }
